name: build
on:
  workflow_dispatch:
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  kryo_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Duse-llvm=true -Dno-lib=true -Dno-langref=true -Ddev=full -Duse-zig-libcxx=true -Dtarget="aarch64-linux-musl" -Dcpu="kryo" -Doptimize=ReleaseFast -Dstrip=true -Dvalue-interpret-mode=direct -Dvalue-tracing=false -fno-reference-trace -Ddebug-extensions=false -Dflat=true --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a kryo_fast.7z nightly
        tar -cJf kryo_fast.tar.xz nightly
        tar -cf kryo_fast.tar nightly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          kryo_fast.tar
          kryo_fast.tar.xz
          kryo_fast.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/
        ls -l nightly/
        
  kryo_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Duse-llvm=true -Dno-lib=true -Dno-langref=true -Ddev=full -Duse-zig-libcxx=true -Dtarget="aarch64-linux-musl" -Dcpu="kryo" -Doptimize=ReleaseSmall -Dstrip=true -Dvalue-interpret-mode=direct -Dvalue-tracing=false -fno-reference-trace -Ddebug-extensions=false -Dflat=true --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a kryo_small.7z nightly
        tar -cJf kryo_small.tar.xz nightly
        tar -cf kryo_small.tar nightly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          kryo_small.tar
          kryo_small.tar.xz
          kryo_small.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/
        ls -l nightly/
        
  x64_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Duse-llvm=true -Dstatic-llvm=false -Dno-lib=true -Dno-langref=true -Ddev=full -Duse-zig-libcxx=true -Doptimize=ReleaseFast -Dstrip=true -Dvalue-interpret-mode=direct -Dvalue-tracing=false -fno-reference-trace -Ddebug-extensions=false -Dflat=true --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a x64_fast.7z nightly
        tar -cJf x64_fast.tar.xz nightly
        tar -cf x64_fast.tar nightly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          x64_fast.tar
          x64_fast.tar.xz
          x64_fast.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/
        ls -l nightly/
