name: build
on:
  push:
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Doptimize=ReleaseFast -Dcpu="cortex_x1c" -Dstrip=true -Dtarget="aarch64-linux-musl" -Dstatic-llvm --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Fast
        path: ./zig-out/**
        
  Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Doptimize=ReleaseSmall -Dcpu="cortex_x1c" -Dstrip=true -Dtarget="aarch64-linux-musl" -Dstatic-llvm --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Small
        path: ./zig-out/**

  EZ:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz"
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Dstatic-llvm --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: EZ
        path: ./zig-out/**
