name: build
on:
  push:
    branches:
    - ez
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
env:
  LINK: 'https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz'
  LLVM_VERSION: 19
  ZIGFLAGS: '-Dtarget=aarch64-linux-musl -Duse-llvm=true -Denable-llvm=true -Dllvm-has-m68k=false -Dllvm-has-csky=false -Dllvm-has-arc=false -Ddev=full -Duse-zig-libcxx=true -Dstrip=true -Dvalue-interpret-mode=direct -Dvalue-tracing=false -fno-reference-trace -Ddebug-extensions=false -Dflat=true --zig-lib-dir /home/runner/work/zig/zig/.zig/zig/lib'
jobs:
  CreatTag:
    runs-on: ubuntu-latest
    steps:
    - if: env.SB == 1
      uses: actions/checkout@v4
    - name: Create a new tag
      if: env.SB == 1
      run: |
        TAG_NAME="nightly"
        git tag $TAG_NAME
        git push origin $TAG_NAME
  help:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: HELP
      run: |
        . .github/workflows/setup.sh
        zig build --help        
  kryo_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        . .github/workflows/setup.sh
        zig build -Doptimize="ReleaseFast" -Dcpu="kryo" $ZIGFLAGS
    - name: Pack output
      run: |
        export NAME="kryo_fast"
        mv .github/workflows/packer.sh .
        chmod +x packer.sh
        ./packer.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          kryo_fast*
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin
        ls -l nightly/bin
        
  kryo_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        . .github/workflows/setup.sh
        zig build -Doptimize="ReleaseSmall" -Dcpu="kryo" $ZIGFLAGS
    - name: Pack output
      run: |
        export NAME="kryo_small"
        mv .github/workflows/packer.sh .
        chmod +x packer.sh
        ./packer.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          kryo_small*
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/





  x1c_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        . .github/workflows/setup.sh
        zig build -Doptimize="ReleaseFast" -Dcpu="cortex_x1c" $ZIGFLAGS
    - name: Pack output
      run: |
        export NAME="x1c_fast"
        mv .github/workflows/packer.sh .
        chmod +x packer.sh
        ./packer.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          x1c_fast*
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/
        
  x1c_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        . .github/workflows/setup.sh
        zig build -Doptimize="ReleaseSmall" -Dcpu="cortex_x1c" $ZIGFLAGS
    - name: Pack output
      run: |
        export NAME="x1c_small"
        mv .github/workflows/packer.sh .
        chmod +x packer.sh
        ./packer.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          x1c_small*
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/





  baseline_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        . .github/workflows/setup.sh
        zig build -Doptimize="ReleaseFast" -Dcpu="baseline" $ZIGFLAGS
    - name: Pack output
      run: |
        export NAME="baseline_fast"
        mv .github/workflows/packer.sh .
        chmod +x packer.sh
        ./packer.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          baseline_fast*
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/
        
  baseline_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        . .github/workflows/setup.sh
        zig build -Doptimize="ReleaseSmall" -Dcpu="baseline" $ZIGFLAGS
    - name: Pack output
      run: |
        export NAME="baseline_small"
        mv .github/workflows/packer.sh .
        chmod +x packer.sh
        ./packer.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          baseline_small*
    - name: Check zig binary size
      run: |
        ls -lh nightly/bin/
        ls -l nightly/bin/
