name: clone and build zig master

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "llvm.sh -h"
      run: |
        curl -fsSL -O https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh && ./llvm.sh -h || echo "QoO0oQOo00OoQ0Qo0"

    - name: "build"
      run: |
        sudo apt-get update
        sudo apt-get install cmake -y

        curl -fsSL -O https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh && sudo ./llvm.sh 21 all
        sudo apt-get install lld-21

        git clone --depth 1 https://codeberg.org/ziglang/zig

        cd zig
        mkdir build
        cd build
        cmake ..
        make install

    - name: "check prefix"
      run: ls -lah zig/build/stage3/bin/zig