name: clone and build zig master

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: push a tag
      run: |
        git tag nightly
        git push origin nightly || echo "tag already exist"

    - name: "llvm.sh -h"
      run: |
        curl -fsSL -O https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh && ./llvm.sh -h || echo "QoO0oQOo00OoQ0Qo0"

    - name: "zig build --help"
      run: |
        mkdir .zig && cd .zig && wget -q https://ziglang.org/builds/zig-x86_64-linux-0.16.0-dev.1892+53ebfde6b.tar.xz
        tar xf zig-x86_64-linux-0.16.0-dev.1892+53ebfde6b.tar.xz
        cd .. && mkdir zig && cd zig/
        wget -q https://ziglang.org/builds/zig-0.16.0-dev.1859+212968c57.tar.xz
        tar xf zig-0.16.0-dev.1859+212968c57.tar.xz
        mv zig-0.16.0-dev.1859+212968c57/* .
        time ../.zig/zig-x86_64-linux-0.16.0-dev.1892+53ebfde6b/zig build --help

    - name: "search libs"
      run: |
        find /usr/lib -name "libz*"

    - name: "build"
      run: |
        sudo apt-get update >/dev/null
        sudo apt-get install cmake zlib1g-dev libzstd-dev -y >/dev/null

        curl -fsSL -O https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh && sudo ./llvm.sh 21 all >/dev/null
        sudo apt-get install lld-21 liblld-21-dev -y >/dev/null

        cd zig && mkdir build && cd build
        # cmake .. -DCMAKE_BUILD_TYPE=Release -DZIG_STATIC=ON -GNinja
        cmake .. -GNinja
        time ninja install
        export PATH=$(pwd)/stage3/bin:$PATH

        cd ../../ && chmod +x deps.sh && ./deps.sh

        cd zig
        time zig build -p stage3 --search-prefix "$(llvm-config-21 --prefix)" --zig-lib-dir "lib" -Dtarget=aarch64-linux-none -Doptimize=ReleaseFast -Dflat -Dstrip -Dstatic-llvm -Dpie -Dversion-string="$(build/stage3/bin/zig version)"

    - name: "check prefix"
      run: |
        ls -lah zig/build/stage3/bin/zig
        ls -lah zig/zig-out
        ls -lah zig/zig-out/*

    - name: "pack to tar.zst"
      run: |
        cd zig
        tar --zstd -cf x86_64-linux-debug.tar.zst build/stage3/
        tar --zstd -cf aarch64-linux-fast.tar.zst zig-out/
        ls -lh x86_64-linux-debug.tar.zst
        ls -lh aarch64-linux-fast.tar.zst

    - uses: softprops/action-gh-release@v2.5.0
      with:
        tag: nightly
        files: |
          zig/x86_64-linux-fast.tar.zst
          zig/aarch64-linux-fast.tar.zst

    - name: "build with single-threaded"
      run: cd zig && time build/stage3/bin/zig build -p stage3 --search-prefix "$(llvm-config-21 --prefix)" --zig-lib-dir "lib" -Dtarget=aarch64-linux-none -Doptimize=ReleaseFast -Dflat -Dstrip -Dstatic-llvm -Dpie -Dsingle-threaded -Dsanitize-thread -Dversion-string="$(build/stage3/bin/zig version)"

    - name: "check single-threaded"
      run: |
        ls -lah zig/zig-out
        ls -lah zig/zig-out/*

