name: Revert Merge

on:
  workflow_dispatch:
  push:
permissions: write-all
jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Revert last merge commit
        run: |
          git config --local user.name "actions"
          git config --local user.email "actions@github.com"
          git revert -m 1 0d6b17b6a5cd4d179417f8a13302558b05f1f2ca
          git push origin master2
