name: Test
on:
  push:

env: 
  LINK: 'https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2847+db8ed730e.tar.xz'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    - name: rec
      run: |
        git config --local user.name "actions"
        git config --local user.email "actions@github.com"
        git revert --no-commit e4d570695777af643e375343a904a024250de98d..0595feb34128db22fbebea843af929de3ede8190
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz $LINK
        tar -xf zig.tar.xz && rm zig.tar.xz
        mv * zig && cd zig && mkdir bin && mv zig bin && export PATH=$PATH:$PWD/bin
        cd ../..
        zig build
