name: TEST
on:
  push:
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  help:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -L -o zig.7z "https://github.com/5hes/zig/releases/download/nightly/x64_fast.7z"
        ls -lh zig.7z
        7z x zig.7z && rm zig.7z
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig zen
        echo -e "\n\n\n\n\n"
        zig --help
        echo -e "\n\n\n\n\n"
        zig build --help
  kroy_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -L -o zig.7z "https://github.com/5hes/zig/releases/download/nightly/x64_fast.7z"
        ls -lh zig.7z
        7z x zig.7z && rm zig.7z
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Dtarget="aarch64-linux-musl" -Dcpu="kryo" -Doptimize=ReleaseFast -Dstrip=true -Dvalue-interpret-mode=direct -Dvalue-tracing=false -fno-reference-trace -Ddebug-extensions=false -Dflat=true --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a TEST_kryo_fast.7z nightly
        tar -cJf TEST_kryo_fast.tar.xz nightly
        tar -cf TEST_kryo_fast.tar nightly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          TEST_kryo_fast.tar
          TEST_kryo_fast.tar.xz
          TEST_kryo_fast.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/
        ls -l nightly/
        
  kryo_Small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -L -o zig.7z "https://github.com/5hes/zig/releases/download/nightly/x64_fast.7z"
        ls -lh zig.7z
        7z x zig.7z && rm zig.7z
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Dtarget="aarch64-linux-musl" -Dcpu="kryo" -Doptimize=ReleaseSmall -Dstrip=true -Dvalue-interpret-mode=direct -Dvalue-tracing=false -fno-reference-trace -Ddebug-extensions=false -Dflat=true --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a TEST_kryo_small.7z nightly
        tar -cJf TEST_kryo_small.tar.xz nightly
        tar -cf TEST_kryo_small.tar nightly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          TEST_kryo_small.tar
          TEST_kryo_small.tar.xz
          TEST_kryo_small.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/
        ls -l nightly/
        
  x64_Fast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        curl -o llvm.sh https://apt.llvm.org/llvm.sh
        sudo chmod 777 llvm.sh
        sudo ./llvm.sh 19 all
    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -L -o zig.7z "https://github.com/5hes/zig/releases/download/nightly/x64_fast.7z"
        ls -lh zig.7z
        7z x zig.7z && rm zig.7z
        mv * zig && cd zig && export PATH=$PATH:$PWD
        cd ../..
        zig build -Doptimize=ReleaseFast -Dstrip=true -Dvalue-interpret-mode=direct -Dvalue-tracing=false -fno-reference-trace -Ddebug-extensions=false -Dflat=true --zig-lib-dir "$PWD/.zig/zig/lib"
    - name: Pack output
      run: |
        mv zig-out nightly
        7z a TEST_x64_Fast.7z nightly
        tar -cJf TEST_x64_Fast.tar.xz nightly
        tar -cf TEST_x64_Fast.tar nightly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        make_latest: true
        files: |
          TEST_x64_fast.tar
          TEST_x64_fast.tar.xz
          TEST_x64_fast.7z
    - name: Check zig binary size
      run: |
        ls -lh nightly/
        ls -l nightly/
